require "awesome_print"
require 'highline/import' #just to do the ask stuff
require_relative "tic_tac_toe/cell"
require_relative "tic_tac_toe/player"
require_relative "tic_tac_toe/computer"
require_relative "tic_tac_toe/game"
require_relative "tic_tac_toe/grid"
require_relative "tic_tac_toe/coordinate"
require_relative "tic_tac_toe/row"
require_relative "tic_tac_toe/column"
require_relative "tic_tac_toe/diagonal"
require_relative "tic_tac_toe/human"
